import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Blog from '@/lib/models/Blog';
import BlogRun, { type IBlogRun } from '@/lib/models/BlogRun';
import { verifyAdminAuth } from '@/lib/admin-auth';

/**
 * Health view for the automated blog pipeline.
 *
 * Answers the two questions an operator actually has: did today's articles
 * publish, and if something broke, what broke. Consumed by the admin page and
 * by the mobile app.
 */

export const dynamic = 'force-dynamic';

const DAILY_LIMIT = Number(process.env.MAX_AUTO_POSTS_PER_DAY || 5);

async function verifyAdmin(request: NextRequest): Promise<boolean> {
  const authHeader = request.headers.get('authorization');
  if (!authHeader?.startsWith('Bearer ')) return false;
  return verifyAdminAuth(authHeader.substring(7));
}

function startOfUtcDay(daysAgo = 0): Date {
  const d = new Date();
  d.setUTCHours(0, 0, 0, 0);
  d.setUTCDate(d.getUTCDate() - daysAgo);
  return d;
}

export async function GET(request: NextRequest) {
  if (!(await verifyAdmin(request))) {
    return NextResponse.json({ success: false, message: 'Unauthorized. Admin access required.' }, { status: 401 });
  }

  try {
    await connectDB();

    const today = startOfUtcDay();
    const weekAgo = startOfUtcDay(6);

    const [todayRuns, weekRuns, recentRuns, publishedToday, totalPosts, latestPosts] = await Promise.all([
      BlogRun.find({ createdAt: { $gte: today } }).sort({ createdAt: -1 }).lean(),
      BlogRun.find({ createdAt: { $gte: weekAgo } }).select('ok skipped createdAt').lean(),
      BlogRun.find({}).sort({ createdAt: -1 }).limit(25).lean(),
      Blog.countDocuments({ autoGenerated: true, createdAt: { $gte: today } }),
      Blog.countDocuments({ autoGenerated: true }),
      Blog.find({ autoGenerated: true })
        .select('slug title category createdAt coverImage readTime')
        .sort({ createdAt: -1 })
        .limit(10)
        .lean(),
    ]);

    const runs = todayRuns as unknown as IBlogRun[];
    const attemptsToday = runs.filter((r) => !r.skipped);
    const failuresToday = attemptsToday.filter((r) => !r.ok);

    // Per-day counts for the last week, oldest first, for a simple trend view.
    const week = Array.from({ length: 7 }, (_, i) => {
      const day = startOfUtcDay(6 - i);
      const next = new Date(day);
      next.setUTCDate(next.getUTCDate() + 1);
      const inDay = (weekRuns as unknown as IBlogRun[]).filter(
        (r) => !r.skipped && r.createdAt >= day && r.createdAt < next
      );
      return {
        date: day.toISOString().slice(0, 10),
        published: inDay.filter((r) => r.ok).length,
        failed: inDay.filter((r) => !r.ok).length,
      };
    });

    const lastRun = (recentRuns as unknown as IBlogRun[])[0] || null;

    // Group failure reasons so a recurring problem is obvious at a glance
    // rather than buried in a list of near-identical rows.
    const reasonCounts = new Map<string, number>();
    for (const run of (recentRuns as unknown as IBlogRun[]).filter((r) => !r.ok && r.reason)) {
      const key = run.reason as string;
      reasonCounts.set(key, (reasonCounts.get(key) || 0) + 1);
    }

    return NextResponse.json({
      success: true,
      today: {
        published: publishedToday,
        failed: failuresToday.length,
        attempts: attemptsToday.length,
        limit: DAILY_LIMIT,
        // The scheduler fires five times a day; anything less means a slot was lost.
        onTrack: publishedToday >= Math.min(DAILY_LIMIT, attemptsToday.length),
      },
      lastRun: lastRun
        ? {
            at: lastRun.createdAt,
            ok: lastRun.ok,
            skipped: lastRun.skipped,
            slug: lastRun.slug,
            title: lastRun.title,
            format: lastRun.format,
            reason: lastRun.reason,
            durationMs: lastRun.durationMs,
          }
        : null,
      week,
      totalAutoPosts: totalPosts,
      failureReasons: [...reasonCounts.entries()]
        .map(([reason, count]) => ({ reason, count }))
        .sort((a, b) => b.count - a.count),
      recentRuns: (recentRuns as unknown as IBlogRun[]).map((r) => ({
        at: r.createdAt,
        ok: r.ok,
        skipped: r.skipped,
        slug: r.slug,
        title: r.title,
        format: r.format,
        words: r.words,
        writerModel: r.writerModel,
        reason: r.reason,
        durationMs: r.durationMs,
      })),
      latestPosts,
    });
  } catch (error) {
    console.error('[admin/blog-status]', error);
    return NextResponse.json(
      { success: false, message: error instanceof Error ? error.message : 'Failed to load blog status' },
      { status: 500 }
    );
  }
}
