import mongoose, { Schema, Document } from 'mongoose';

export interface IBlogContent {
  type: 'paragraph' | 'heading' | 'list' | 'quote';
  content: string | string[];
}

export interface IBlog extends Document {
  slug: string;
  title: {
    en: string;
    tr: string;
  };
  excerpt: {
    en: string;
    tr: string;
  };
  /** The English body. Served at /blog/<slug>. */
  content: IBlogContent[];
  /**
   * The Turkish body, served at /tr/blog/<slug>. Same article, same slug, same
   * block structure — one piece of journalism in two languages rather than two
   * separate archives. Absent only when translation failed and has not yet been
   * retried, in which case the Turkish page falls back to the English body.
   */
  contentTr?: IBlogContent[];
  /**
   * The film and series names this article is grounded in, exactly as TMDB
   * spells them. Kept so a translation can be redone later and still copy the
   * titles verbatim instead of rendering "Fall 2: Deadpoint" into Turkish.
   */
  sourceTitles?: string[];
  date: string;
  readTime: string;
  category: string;
  author: string;
  tags: string[];
  coverImage?: string;
  isPublished: boolean;
  /**
   * The language this article was composed in, before translation. Informational
   * only — it does not decide which edition a post appears in, because every
   * post appears in both.
   */
  lang?: 'en' | 'tr';
  /** True for posts written by the automated Groq pipeline (lib/blog-generator). */
  autoGenerated?: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const BlogContentSchema = new Schema({
  type: {
    type: String,
    enum: ['paragraph', 'heading', 'list', 'quote'],
    required: true
  },
  content: {
    type: Schema.Types.Mixed,
    required: true
  }
}, { _id: false });

const BlogSchema = new Schema<IBlog>({
  slug: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    lowercase: true
  },
  title: {
    en: { type: String, required: true },
    tr: { type: String, required: true }
  },
  excerpt: {
    en: { type: String, required: true },
    tr: { type: String, required: true }
  },
  content: [BlogContentSchema],
  contentTr: [BlogContentSchema],
  sourceTitles: [{ type: String }],
  date: {
    type: String,
    required: true
  },
  readTime: {
    type: String,
    required: true
  },
  category: {
    type: String,
    required: true
  },
  author: {
    type: String,
    default: 'WatchPulse Team'
  },
  tags: [{
    type: String
  }],
  coverImage: {
    type: String
  },
  isPublished: {
    type: Boolean,
    default: true
  },
  lang: {
    type: String,
    enum: ['en', 'tr'],
    default: 'en'
  },
  autoGenerated: {
    type: Boolean,
    default: false
  }
}, {
  timestamps: true
});

// Indexes for better performance (slug index already defined via unique: true)
BlogSchema.index({ category: 1 });
BlogSchema.index({ isPublished: 1 });
BlogSchema.index({ createdAt: -1 });
// Backs the cron's "how many did we auto-publish today?" guard.
BlogSchema.index({ autoGenerated: 1, createdAt: -1 });
// Both editions list the same posts, so the index listings are not scoped by
// language: they page the archive newest-first, optionally within a category.
BlogSchema.index({ isPublished: 1, createdAt: -1 });
BlogSchema.index({ isPublished: 1, category: 1, createdAt: -1 });
// Backs the repair pass's "which article is still missing its Turkish side?"
// lookup, which runs on every scheduled publish and must stay cheap when the
// answer is "none" — the normal case.
BlogSchema.index({ isPublished: 1, contentTr: 1 });

// Dedicated collection: the backend keeps its own `blogs` collection (backend
// schema); the website reads/writes the mirrored website-schema docs in `webblogs`.
export default mongoose.models.Blog || mongoose.model<IBlog>('Blog', BlogSchema, 'webblogs');
